### PR TITLE
Return partial function instead of local scoped function

### PR DESCRIPTION
**Pull request by giuliabaldini**
Returning a partial function instead of a local-scoped function allows for the function to be pickled, which is useful when using multiprocessing.

### CODE REVIEW

**Comment by ir4y** [comment]
Hi @giuliabaldini 
Thank you for your contribution.
Could you please pull the recent main branch changes to your pull request, I have fixed CI/CD and want to check that the build pass with your changes.

**Comment by giuliabaldini** [comment]
Hey! Thank you for your reply. The workflow will only run if you approve it, I think. The only problem with using `partial` is that the `context` variable cannot be passed as a positional argument, only as a keyword argument. There are multiple workarounds for this, but I just wanted to know if you think this might be useful to begin with.

**Comment by ir4y** [comment]
@giuliabaldini It is highly important to keep backward compatibilities.
You can check how fhirpath-py is used in another project:
https://github.com/beda-software/aidbox-sdc/blob/317faf30efabccc20223f34601566b2f5c6e5655/app/operations/populate.py#L69

So, the fix to support context as a positional argument is required before merging.

**Comment by giuliabaldini** [comment]
@ir4y Yeah I understand, the best would have been to change the order of the parameters of the `apply_parsed_path` function, but since the package is already published and established, it should just be fixed in other ways. At the beginning, I didn't know if I was going to get an answer, and I was just thinking about extending the package in the fork, but since you are working on it, I can totally add new features and push them for review.
 
So by the way, I added a fix to the problem. 
The fix is general and can be used for any function, it ensures pickling since it is a class, and preserves the order of the arguments by checking the function's signature with `inspect`. There is a bit of overhead because it needs to check which arguments are there, so if you prefer it I could push a custom class only for this particular case, which would look like this:
```
class PathEvaluator:
    def __init__(self, func, **preset_args):
        self.func = func
        self.preset_args = preset_args

    def __call__(self, resource, context={}):
        return self.func(resource=resource, context=context, **self.preset_args)
```
and use that instead.

Best,
Giulia

**Comment by ir4y** [comment]
I think it makes sense to implement a more simple solution. We don't need a universal `partial_with_args` implementation.
Please feel free to simplify the code of `partial_with_args` to achieve one particular goal.

**Comment by giuliabaldini** [comment]
Where would you like me to add it? In `test_real.py`?

**Comment by giuliabaldini** [comment]
I added it there, tell me if I should move it.

**Pull request merged**
